<?php
/**
 * Site header. Navigation mirrors the static site; edit the links here.
 * @package CityPulse
 */
?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<a class="skip" href="#main">Skip to content</a>
<header class="site-header">
  <div class="wrap header-inner">
    <a class="brand" href="<?php echo esc_url( home_url( '/' ) ); ?>" aria-label="CityPulse Kiosks home"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/' ) ); ?>logo.svg" alt="CityPulse Kiosks" width="380" height="116"></a>
    <button class="nav-toggle" aria-expanded="false" aria-controls="site-nav"><span class="sr">Menu</span><i></i><i></i></button>
    <nav id="site-nav" class="site-nav" aria-label="Main">
      <a href="<?php echo esc_url( home_url( '/' ) ); ?>kiosk/"<?php citypulse_current_attr( 'kiosk/' ); ?>>The kiosk</a>
      <div class="nav-item<?php citypulse_current_class( 'advertise', array( 'advertise/','pricing/','campaign-planner/','creative-studio/','campaign-ideas/','audience/','locations/','agencies/' ) ); ?>"><button class="nav-btn" aria-expanded="false" aria-controls="menu-advertise">Advertise<svg class="" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg></button><div class="mega" id="menu-advertise"><a href="<?php echo esc_url( home_url( '/' ) ); ?>advertise/" class="mega-lead"><b>Advertise with CityPulse</b><span>Placements, pricing and how a campaign comes together</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>pricing/"><b>Pricing & calculator</b><span>Annual rates and a multi-kiosk estimate</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>campaign-planner/"><b>Campaign planner</b><span>Build a brief step by step</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>creative-studio/"><b>Creative studio</b><span>Preview your message on the kiosk</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>campaign-ideas/"><b>Campaign ideas</b><span>Eight local playbooks to adapt</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>audience/"><b>Who you can reach</b><span>Visitor moments in each venue</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>locations/"><b>Market planning</b><span>Cities and regions in our plans</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>agencies/"><b>For agencies</b><span>Start with a client brief</span></a></div></div>
      <div class="nav-item<?php citypulse_current_class( 'venues', array( 'hosts/','venues/','resources/host-preparation/','venues/hotels/','venues/medical/','venues/automotive/','venues/restaurants/' ) ); ?>"><button class="nav-btn" aria-expanded="false" aria-controls="menu-venues">For venues<svg class="" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg></button><div class="mega" id="menu-venues"><a href="<?php echo esc_url( home_url( '/' ) ); ?>hosts/" class="mega-lead"><b>Host a kiosk</b><span>The managed offering, at no cost for qualified venues</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>venues/"><b>Venues overview</b><span>Where CityPulse fits</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>resources/host-preparation/"><b>Prepare your venue</b><span>What to have ready for a first call</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>venues/hotels/"><b>Hotels & hospitality</b><span>A useful lobby experience</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>venues/medical/"><b>Medical offices</b><span>Information while visitors wait</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>venues/automotive/"><b>Car dealerships</b><span>Sales and service lounges</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>venues/restaurants/"><b>Restaurants & venues</b><span>Menus, events and local discovery</span></a></div></div>
      <div class="nav-item<?php citypulse_current_class( 'resources', array( 'resources/','how-it-works/','media-kit/','resources/first-local-campaign/','resources/screen-creative/','measurement/','faqs/','support/' ) ); ?>"><button class="nav-btn" aria-expanded="false" aria-controls="menu-resources">Resources<svg class="" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg></button><div class="mega" id="menu-resources"><a href="<?php echo esc_url( home_url( '/' ) ); ?>resources/" class="mega-lead"><b>All resources</b><span>Guides, tools and inspiration</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>how-it-works/"><b>How it works</b><span>The advertiser and host journeys</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>media-kit/"><b>Media overview</b><span>The concept in one place</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>resources/first-local-campaign/"><b>First campaign guide</b><span>From goal to a useful brief</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>resources/screen-creative/"><b>Creative guide</b><span>A screen message people can read</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>measurement/"><b>Measurement guide</b><span>What the numbers mean</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>faqs/"><b>Common questions</b><span>Answers for advertisers and hosts</span></a><a href="<?php echo esc_url( home_url( '/' ) ); ?>support/"><b>Help & support</b><span>For existing kiosks and campaigns</span></a></div></div>
      <a href="<?php echo esc_url( home_url( '/' ) ); ?>about/"<?php citypulse_current_attr( 'about/' ); ?>>About</a>
      <a class="btn btn-small header-cta" href="<?php echo esc_url( home_url( '/' ) ); ?>#get-started">Get started — $399</a>
    </nav>
  </div>
</header>
