/* Packs Sales Studio (sales/shell.html + sales/app.html) into sales-page.js, which the worker serves at /sales.
   Run after editing either file: node cloudflare/build-sales.mjs
   sales/app.html is the same CRM page that also runs inside Claude; shell.html adds sign-in and the server connection. */
import { readFileSync, writeFileSync } from "node:fs";
const dir = new URL(".", import.meta.url);
const app = readFileSync(new URL("sales/app.html", dir), "utf8");
const shell = readFileSync(new URL("sales/shell.html", dir), "utf8");
const styleEnd = app.indexOf("</style>") + "</style>".length;
const scriptStart = app.indexOf("<script>"), scriptEnd = app.lastIndexOf("</script>");
if (styleEnd < 8 || scriptStart < 0 || scriptEnd < scriptStart) throw new Error("app.html layout changed: expected head, markup, one <script>");
const head = app.slice(0, styleEnd), markup = app.slice(styleEnd, scriptStart), code = app.slice(scriptStart + 8, scriptEnd);
if (/<\/script|<!--/i.test(code)) throw new Error("app script must not contain </script or <!--");
const html = shell.replace("<!--APP_HEAD-->", () => head).replace("<!--APP_MARKUP-->", () => markup).replace("<!--APP_SCRIPT-->", () => code);
writeFileSync(new URL("sales-page.js", dir), "/* Generated by build-sales.mjs from sales/shell.html and sales/app.html. Edit those files, not this one. */\nexport const SALES_HTML = " + JSON.stringify(html) + ";\n");
console.log("sales-page.js written,", html.length, "bytes");
