/* Packs the dashboard (admin/index.html and admin/app.js) into admin-page.js, which the worker serves.
   Run after editing the dashboard: node cloudflare/build-admin.mjs */
import { readFileSync, writeFileSync } from "node:fs";
const dir = new URL(".", import.meta.url);
const html = readFileSync(new URL("admin/index.html", dir), "utf8");
const js = readFileSync(new URL("admin/app.js", dir), "utf8");
/* CityPulse logos, taken from the website's own files so they always match */
const brand = Object.fromEntries(["logo.svg", "logo-light.svg", "logo-mark.svg", "favicon.svg"].map(f => [f, readFileSync(new URL("../assets/" + f, dir), "utf8")]));
writeFileSync(new URL("admin-page.js", dir),
  "/* Generated by build-admin.mjs from admin/index.html and admin/app.js. Edit those files, not this one. */\n" +
  "export const ADMIN_HTML = " + JSON.stringify(html) + ";\n" +
  "export const ADMIN_JS = " + JSON.stringify(js) + ";\n" +
  "export const ADMIN_BRAND = " + JSON.stringify(brand) + ";\n");
console.log("admin-page.js written");
